#docker network create -d overlay --attachable docker-browser2_default
version: '3.3'
networks:
  docker-browser2_default:
    driver: overlay
    external:
      name:  docker-browser2_default
services:
  
  whoami:
    
    image: jwilder/whoami
    labels:
      - traefik.http.routers.whoami.rule=Host(`whoami.labs.dappsuni.com`)
      #- traefik.http.routers.whoami.tls=true
      #- traefik.http.routers.whoami.tls.certresolver=lets-encrypt
      #- traefik.port=80
      #- traefik.http.routers.whoami.entrypoints: web
      - traefik.http.routers.whoami.service=whoami
      - traefik.http.services.whoami.loadbalancer.server.port=8000
      - traefik.docker.network=docker-browser2_default
    
    networks:
      docker-browser2_default:
        #external:
          #name:  docker-browser2_default
  
  crypto:
    
    image: eshnil2000/crypto-trading
    labels:
      - traefik.http.routers.crypto.rule=Host(`crypto.labs.dappsuni.com`)
      #- traefik.http.routers.crypto.tls=true
      #- traefik.http.routers.crypto.tls.certresolver=lets-encrypt
      #- traefik.port=80
      #- traefik.http.routers.crypto.entrypoints: web
      - traefik.http.routers.crypto.service=crypto
      - traefik.http.services.crypto.loadbalancer.server.port=5000
      - traefik.docker.network=docker-browser2_default
    
    networks:
      docker-browser2_default:
        #external:
          #name:  docker-browser2_default  